package fr.planb.gerald.reynier.Model;

import javax.persistence.*;

/**
 * 
 * @author Laurence REYNIER
 * I do not know yet on which JVM we will run this application,
 * that's why I use the interface SERIALIZABLE which allows the 
 * use to exchange objects on different JVM,
 * to facilitate the persistence of the data and to save a configuration, ... 
 * @Entity : mandatory annotation in JPA (Java Persistance Api : java specifications to 
 * persist data, hibernate (for example) is an JPA implementation
 *
 */

/** 
 * @author Laurence REYNIER
 * My Entities will be database and Tables will be table : their names 
 * will be prefixed with a "t".
 * This Entity Person, is the customers' database
 * I use french name for columns' name because this application is made for a french society
 * names in Entity are in English
 */
@Entity (name = "personne")
@Table(name="tpersonne")
public class Person {
	
	//autoincremental id, in Talend : default length for integer is 19, I kept
	//this convention
	//strategy : is an attribute to define generator type to use, AUTO is a default value
	//but I wanted to use it for memory
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "idPersonne", length = 19, nullable= true, unique = true)
	private long idPersonne;
	
	//Firstname
	@Basic(optional =  false)
	@Column(name = "nom", length = 255, nullable= true, unique = true)
	private String firstName;
	
	//lastname
	@Basic(optional =  false)
	@Column(name = "prenom", length = 255, nullable= true, unique = true)
	private String lastName;	
	
	@Basic(optional =  false)
	@Column(name = "email", length = 255, nullable= true, unique = true)
	private String eMail;	
	
	@Basic(optional =  false)
	@Column(name = "telmobile", length = 19, nullable= true, unique = true)
	private long mobile;	
	
	@Basic(optional =  false)
	@Column(name = "adresse", length = 255, nullable= true, unique = true)
	private String address;	
	
	@Basic(optional =  false)
	@Column(name = "codepostal", length = 19, nullable= true, unique = true)
	private long postalCode;
	
	@Basic(optional =  false)
	@Column(name = "ville", length = 255, nullable= true, unique = true)
	private String country;	
	
	@Basic(optional =  false)
	@Column(name = "teldomicile", length = 19, nullable= true, unique = true)
	private long homePhone;	
	
	@Basic(optional =  false)
	@Column(name = "telprofession", length = 19, nullable= true, unique = true)
	private long jobPhone;	
	
	//for qrCode : I use a length to 8000 (max of String) because a qrCode could have
	//7089 numbers, 4296 alphanumerics, 2953 binary, ...
	//total of needs is 1300 about. It is enough for this Entity
	@Basic(optional =  false)
	@Column(name = "qrcode", length = 8000, nullable= true, unique = true)
	private String qrCode;

	/**
	 * Constructors generated with : Source tag
	 * empty and overrided Constructors
	 */
	public Person() {
		super();
	}

	/**
	 * @param idPersonne
	 * @param firstName
	 * @param lastName
	 * @param eMail
	 * @param mobile
	 * @param address
	 * @param postalCode
	 * @param country
	 * @param homePhone
	 * @param jobPhone
	 * @param qrCode
	 */
	public Person(long idPersonne, String firstName, String lastName, String eMail, long mobile, String address,
			long postalCode, String country, long homePhone, long jobPhone, String qrCode) {
		super();
		this.idPersonne = idPersonne;
		this.firstName = firstName;
		this.lastName = lastName;
		this.eMail = eMail;
		this.mobile = mobile;
		this.address = address;
		this.postalCode = postalCode;
		this.country = country;
		this.homePhone = homePhone;
		this.jobPhone = jobPhone;
		this.qrCode = qrCode;
	}

	// Getters or accessors, and setters or mutators are generated by source tag
	/**
	 * @return the idPersonne
	 */
	public long getIdPersonne() {
		return idPersonne;
	}

	/**
	 * @param idPersonne the idPersonne to set
	 */
	public void setIdPersonne(long idPersonne) {
		this.idPersonne = idPersonne;
	}

	/**
	 * @return the firstName
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * @param firstName the firstName to set
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * @return the lastName
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * @param lastName the lastName to set
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * @return the eMail
	 */
	public String geteMail() {
		return eMail;
	}

	/**
	 * @param eMail the eMail to set
	 */
	public void seteMail(String eMail) {
		this.eMail = eMail;
	}

	/**
	 * @return the mobile
	 */
	public long getMobile() {
		return mobile;
	}

	/**
	 * @param mobile the mobile to set
	 */
	public void setMobile(long mobile) {
		this.mobile = mobile;
	}

	/**
	 * @return the address
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * @param address the address to set
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * @return the postalCode
	 */
	public long getPostalCode() {
		return postalCode;
	}

	/**
	 * @param postalCode the postalCode to set
	 */
	public void setPostalCode(long postalCode) {
		this.postalCode = postalCode;
	}

	/**
	 * @return the country
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * @param country the country to set
	 */
	public void setCountry(String country) {
		this.country = country;
	}

	/**
	 * @return the homePhone
	 */
	public long getHomePhone() {
		return homePhone;
	}

	/**
	 * @param homePhone the homePhone to set
	 */
	public void setHomePhone(long homePhone) {
		this.homePhone = homePhone;
	}

	/**
	 * @return the jobPhone
	 */
	public long getJobPhone() {
		return jobPhone;
	}

	/**
	 * @param jobPhone the jobPhone to set
	 */
	public void setJobPhone(long jobPhone) {
		this.jobPhone = jobPhone;
	}

	/**
	 * @return the qrCode
	 */
	public String getQrCode() {
		return qrCode;
	}

	/**
	 * @param qrCode the qrCode to set
	 */
	public void setQrCode(String qrCode) {
		this.qrCode = qrCode;
	}	
	
	
}


